# Generated by Django 2.2.6 on 2019-10-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191003_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbooks',
            name='number_of_days',
        ),
        migrations.CreateModel(
            name='RentedDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='borrowedbooks',
            name='rented_days',
            field=models.ManyToManyField(to='books.RentedDuration'),
        ),
    ]
